# libzip
#
# This module defines:
# ZIP_INCLUDE_DIRS
# ZIP_LIBRARIES
#

find_path(ZIP_INCLUDE_DIR_ZIP_H NAMES zip.h)
find_path(ZIP_INCLUDE_DIR_ZIPCONF_H NAMES zipconf.h)
find_library(ZIP_LIBRARY NAMES zip)

include(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(
    ZIP DEFAULT_MSG
    ZIP_INCLUDE_DIR_ZIP_H ZIP_INCLUDE_DIR_ZIPCONF_H ZIP_LIBRARY)

set(ZIP_INCLUDE_DIRS ${ZIP_INCLUDE_DIR_ZIP_H} ${ZIP_INCLUDE_DIR_ZIPCONF_H})
set(ZIP_LIBRARIES ${ZIP_LIBRARY})

